pr

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -1,4 +1,3 @@
-
 name: Pull Request Validation
 
 on:
@@ -8,40 +7,33 @@ on:
       - edited
       - synchronize
 
-permissions: write-all
+permissions:
+  contents: read
+  actions: read
+  checks: write
 
 env:
   DOTNET_VERSION: '8.0'
-  DOTNET_ARTIFACT_NAME: 'dotnet_published_projects'
-  
-  
-jobs: 
 
-  build:
-    runs-on: large
+
+jobs:
+  
+  build-and-test:
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      - name: Setup dotnet
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: '8.x'
       - name: Build
-        uses: AgicapTech/shared-dotnet-action-lib/build@v0.3.22
-        with:
-          vault_auth_role: ${{ vars.VAULT_AUTH_ROLE }}
-          dotnet_version: ${{ env.DOTNET_VERSION }}
-          artifact_name: ${{ env.DOTNET_ARTIFACT_NAME }}
-          projects_to_publish: |
-            NFluentJsonChecks
-            NFluentJsonChecks.Tests
-
-  test:
-    runs-on: large
-    needs: 
-      - build
-    steps:
-      - uses: actions/checkout@v4
+        run: DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_NOLOGO=true dotnet build -m -graph -c Release
       - name: Test
-        uses: AgicapTech/shared-dotnet-action-lib/test@v0.3.22
+        run: DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_NOLOGO=true dotnet test -c Release --no-build --no-restore -v q --logger "trx;LogFileName=$project.trx" || error=true
+      - name: Report tests results
+        uses: dorny/test-reporter@v1
         with:
-          dotnet_version: ${{ env.DOTNET_VERSION }}
-          artifact_name: ${{ env.DOTNET_ARTIFACT_NAME }}
-          test_report_name: dotnet_test_results
-          projects_to_test: |
-            NFluentJsonChecks.Tests/NFluentJsonChecks.Tests.dll
+          name: 'Tests report'
+          path: '**/*.trx'
+          reporter: dotnet-trx
+          fail-on-error: true
